-- Validation before Bronze: the required-column mapping, the staging schema and the
-- business's control table that decides, file by file, what Bronze does.

CREATE SCHEMA IF NOT EXISTS {bronze};
CREATE SCHEMA IF NOT EXISTS {staging};

-- Which file column is which required column, per profit center. Seeded from the Silver
-- DRT mapping (reference_service.seed_bronze_mapping); every mapping a reviewer stages
-- that is not here yet is added. file_columns is the header exactly as the file wrote it.
CREATE TABLE IF NOT EXISTS {bronze}.bronze_column_mapping (
    profit_center      text NOT NULL,
    file_columns       text NOT NULL,
    silver_column_name text NOT NULL,
    -- drt (seeded) | saved | exact | fuzzy | semantic | ai | reviewer
    method             text NOT NULL,
    created_by         text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    UNIQUE (profit_center, file_columns, silver_column_name)
);

-- The control table. The first nine columns are the business's (assets/control_table 1.xlsx,
-- in its order), then the rest of the business's schema, then what the app needs to stage
-- and load a file. control_id is incremental: the seeded rows keep theirs, new files follow.
CREATE TABLE IF NOT EXISTS {control}.control_table (
    control_id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system            text NOT NULL,
    file_name                text NOT NULL,
    reporting_period_type    text,
    processing_action        text,
    bronze_load_flag         char(1) NOT NULL DEFAULT 'N',
    file_received_date       date,
    drt_reporting_start_date date,
    drt_reporting_end_date   date,
    -- AED / PED / TED: the date column the reporting dates came from; NULL when they were
    -- provided (by the business or the reviewer).
    date_detail              text,
    file_replaced            text,
    is_active                char(1) NOT NULL DEFAULT 'Y',
    pc_id                    text,
    division_name            text,
    file_sha256              text,
    job_id                   text,
    output_id                text,
    sheet_names              text[] NOT NULL DEFAULT '{}',
    staging_table            text,
    bronze_table             text,
    ingestion_id             text,
    rejection_reason         text,
    -- The column mapping, AED/PED/TED statistics and per-month statistics at staging time.
    validation               jsonb,
    -- YYYY-MM: the month a monthly file replaced in an earlier load.
    replace_month            text,
    created_by               text,
    created_at               timestamptz NOT NULL DEFAULT now(),
    staged_at                timestamptz,
    loaded_at                timestamptz,
    CHECK (bronze_load_flag IN ('Y', 'N')),
    CHECK (is_active IN ('Y', 'N')),
    CHECK (processing_action IS NULL OR processing_action IN ('INSERT', 'APPEND', 'REJECTED')),
    CHECK (reporting_period_type IS NULL OR reporting_period_type IN ('YTD', 'MONTHLY')),
    CHECK (date_detail IS NULL OR date_detail IN ('AED', 'PED', 'TED'))
);
-- One pending row per file output: a seeded row, or a file staged and not loaded yet. A
-- file sent again after it was loaded or rejected gets a row of its own; the earlier
-- one stays as the record of what happened to it.
CREATE UNIQUE INDEX IF NOT EXISTS control_table_pending
    ON {control}.control_table (source_system, file_name, coalesce(output_id, ''))
    WHERE bronze_load_flag = 'N' AND processing_action IS DISTINCT FROM 'REJECTED';
CREATE INDEX IF NOT EXISTS control_table_loaded
    ON {control}.control_table (source_system, bronze_load_flag, is_active);

-- Each bronze load's control row and reporting dates, beside its YYYY-MM period.
ALTER TABLE {control}.ingestion ADD COLUMN IF NOT EXISTS control_id integer;
ALTER TABLE {control}.ingestion ADD COLUMN IF NOT EXISTS reporting_start_date date;
ALTER TABLE {control}.ingestion ADD COLUMN IF NOT EXISTS reporting_end_date date;
ALTER TABLE {control}.ingestion ADD COLUMN IF NOT EXISTS reporting_period_type text;

-- file_date is the file received date: say so. (Bronze tables are renamed by
-- bronze_service.upgrade_tables, which knows them from the registry.)
DO $$
BEGIN
    ALTER TABLE {control}.ingestion RENAME COLUMN file_date TO file_received_date;
EXCEPTION WHEN undefined_column THEN
    NULL;
END $$;
