-- sheet_name beside file_name in the control table: the sheet a row's table came from, or
-- its sheets, comma-separated, when the cleaner stacked sheets of one layout into one
-- table. With it the control table says what happened to each sheet of a file, not only
-- to the file.
--
-- Postgres only adds a column at the end, and the control table is read in its column
-- order, so the table is rebuilt with sheet_name in place. Every row keeps its control_id
-- and new ones are numbered on from the highest; staged rows get their sheets from
-- sheet_names.

CREATE TEMP TABLE control_table_007 ON COMMIT DROP AS SELECT * FROM {control}.control_table;
DROP TABLE {control}.control_table;

-- The business's nine columns (assets/control_table 1.xlsx, in its order) with sheet_name
-- beside file_name, then the rest of the business's schema, then what the app needs to
-- stage and load a file. control_id is incremental: the seeded rows keep theirs, new files
-- follow.
CREATE TABLE {control}.control_table (
    control_id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system            text NOT NULL,
    file_name                text NOT NULL,
    sheet_name               text,
    reporting_period_type    text,
    processing_action        text,
    bronze_load_flag         char(1) NOT NULL DEFAULT 'N',
    file_received_date       date,
    drt_reporting_start_date date,
    drt_reporting_end_date   date,
    -- AED / PED / TED: the date column the reporting dates came from; NULL when they were
    -- provided (by the business or the reviewer).
    date_detail              text,
    file_replaced            text,
    is_active                char(1) NOT NULL DEFAULT 'Y',
    pc_id                    text,
    division_name            text,
    file_sha256              text,
    job_id                   text,
    output_id                text,
    sheet_names              text[] NOT NULL DEFAULT '{}',
    staging_table            text,
    bronze_table             text,
    ingestion_id             text,
    rejection_reason         text,
    -- The column mapping, AED/PED/TED statistics and per-month statistics at staging time.
    validation               jsonb,
    -- YYYY-MM: the month a monthly file replaced in an earlier load.
    replace_month            text,
    created_by               text,
    created_at               timestamptz NOT NULL DEFAULT now(),
    staged_at                timestamptz,
    loaded_at                timestamptz,
    CHECK (bronze_load_flag IN ('Y', 'N')),
    CHECK (is_active IN ('Y', 'N')),
    CHECK (processing_action IS NULL OR processing_action IN ('INSERT', 'APPEND', 'REJECTED')),
    CHECK (reporting_period_type IS NULL OR reporting_period_type IN ('YTD', 'MONTHLY')),
    CHECK (date_detail IS NULL OR date_detail IN ('AED', 'PED', 'TED'))
);

INSERT INTO {control}.control_table (
    control_id, source_system, file_name, sheet_name, reporting_period_type, processing_action,
    bronze_load_flag, file_received_date, drt_reporting_start_date, drt_reporting_end_date, date_detail,
    file_replaced, is_active, pc_id, division_name, file_sha256, job_id, output_id, sheet_names,
    staging_table, bronze_table, ingestion_id, rejection_reason, validation, replace_month, created_by,
    created_at, staged_at, loaded_at)
SELECT
    control_id, source_system, file_name, nullif(array_to_string(sheet_names, ', '), ''), reporting_period_type,
    processing_action, bronze_load_flag, file_received_date, drt_reporting_start_date, drt_reporting_end_date,
    date_detail, file_replaced, is_active, pc_id, division_name, file_sha256, job_id, output_id, sheet_names,
    staging_table, bronze_table, ingestion_id, rejection_reason, validation, replace_month, created_by,
    created_at, staged_at, loaded_at
FROM control_table_007
ORDER BY control_id;

SELECT setval(pg_get_serial_sequence('{control}.control_table', 'control_id'),
              coalesce((SELECT max(control_id) FROM {control}.control_table), 0) + 1, false);

-- As in 006.
CREATE UNIQUE INDEX control_table_pending
    ON {control}.control_table (source_system, file_name, coalesce(output_id, ''))
    WHERE bronze_load_flag = 'N' AND processing_action IS DISTINCT FROM 'REJECTED';
CREATE INDEX control_table_loaded
    ON {control}.control_table (source_system, bronze_load_flag, is_active);
